# Generated by Django 3.2 on 2021-09-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210831_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.CharField(default='youth', max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
