# Generated by Django 3.2 on 2021-09-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='your', max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
